services:
  couchdb:
    image: couchdb:latest
    container_name: obsidian-livesync
    user: root
    environment:
      hostname: "${HOSTNAME}:5984"
      COUCHDB_USER: $COUCHDB_USER
      COUCHDB_PASSWORD: $COUCHDB_PASSWORD
    volumes:
      - ${BASE_PATH}/config/couchdb-data:/opt/couchdb/data
      - ${BASE_PATH}/config/couchdb-etc:/opt/couchdb/etc/local.d
    restart: unless-stopped
    networks:
      - homelab
