services:

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    depends_on:
      - transmission-openvpn
    network_mode: "service:transmission-openvpn"
    environment:
      PUID: 1000
      PGID: 1000
      LOG_LEVEL: debug
      TZ: Etc/UTC
    volumes:
      - ${BASE_PATH}/config/jellyseerr/config:/app/config
    restart: unless-stopped
    healthcheck:
      # Verify that the transmission-openvpn container is running
      test: ["CMD", "curl", "-f", "http://localhost:9091"] 
      interval: 30s
      timeout: 2s
      retries: 20
    labels:
      autoheal: true
    entrypoint: ["sh", "-c"]  # Override entrypoint to run shell commands
    command: >
      "apk add --no-cache curl &&
      /sbin/tini -- pnpm start"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - transmission-openvpn
    network_mode: "service:transmission-openvpn"
    volumes:
      - ${BASE_PATH}/config/prowlarr/config:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    restart: unless-stopped
    healthcheck:
      # Verify that the transmission-openvpn container is running
      test: ["CMD", "curl", "-f", "http://localhost:9091"] 
      interval: 30s
      timeout: 2s
      retries: 20
    labels:
      autoheal: true

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    depends_on:
      - transmission-openvpn
    network_mode: "service:transmission-openvpn"
    environment:
      PUID: 1000
      PGID: 1000
      LOG_LEVEL: debug
    restart: unless-stopped
    healthcheck:
      # Verify that the transmission-openvpn container is running
      test: ["CMD", "curl", "-f", "http://localhost:9091"] 
      interval: 30s
      timeout: 2s
      retries: 20
    labels:
      autoheal: true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - transmission-openvpn
    network_mode: "service:transmission-openvpn"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ${BASE_PATH}/config/sonarr/config:/config
      - /data:/transcend # All the media containers use transcend internally because that's what i set originally. It's too much work to change it now.
    restart: unless-stopped
    healthcheck:
      # Verify that the transmission-openvpn container is running
      test: ["CMD", "curl", "-f", "http://localhost:9091"] 
      interval: 30s
      timeout: 2s
      retries: 20
    labels:
      autoheal: true

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - transmission-openvpn
    network_mode: "service:transmission-openvpn"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ${BASE_PATH}/config/radarr/config:/config
      - /data:/transcend # All the media containers use transcend internally because that's what i set originally. It's too much work to change it now.
    restart: unless-stopped
    healthcheck:
      # Verify that the transmission-openvpn container is running
      test: ["CMD", "curl", "-f", "http://localhost:9091"] 
      interval: 30s
      timeout: 2s
      retries: 20
    labels:
      autoheal: true

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    depends_on:
      - transmission-openvpn
    network_mode: "service:transmission-openvpn"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ${BASE_PATH}/config/bazarr/config:/config
      - /data:/transcend # All the media containers use transcend internally because that's what i set originally. It's too much work to change it now.
    restart: unless-stopped
    healthcheck:
      # Verify that the transmission-openvpn container is running
      test: ["CMD", "curl", "-f", "http://localhost:9091"] 
      interval: 30s
      timeout: 2s
      retries: 20
    labels:
      autoheal: true

  readarr-audiobooks:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr-audiobooks
    depends_on:
      - transmission-openvpn
    network_mode: "service:transmission-openvpn"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ${BASE_PATH}/config/readarr-audiobooks/config:/config
      - /data:/transcend  # All the media containers use transcend internally because that's what i set originally. It's too much work to change it now.
    restart: unless-stopped
    healthcheck:
      # Verify that the transmission-openvpn container is running
      test: ["CMD", "curl", "-f", "http://localhost:9091"] 
      interval: 30s
      timeout: 2s
      retries: 20
    labels:
      autoheal: true