include:
  - compose-files/management/compose.yaml
  - compose-files/openvpn-transmission/compose.yaml
  - compose-files/servarr/compose.yaml
  - compose-files/media/compose.yaml
  - compose-files/tools/compose.yaml
  # - compose-files/gitlab/compose.yaml

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_VAR_SONARR_API_KEY: $SONARR_API_KEY
      HOMEPAGE_VAR_RADARR_API_KEY: $RADARR_API_KEY
      HOMEPAGE_VAR_JELLYFIN_API_KEY: $JELLYFIN_API_KEY
      HOMEPAGE_VAR_CALIBRE_USERNAME: $CALIBRE_USERNAME
      HOMEPAGE_VAR_CALIBRE_PASSWORD: $CALIBRE_PASSWORD
      HOMEPAGE_VAR_BAZARR_API_KEY: $BAZARR_API_KEY
      HOMEPAGE_VAR_JELLYSEERR_API_KEY: $JELLYSEERR_API_KEY
      HOMEPAGE_VAR_PROWLARR_API_KEY: $PROWLARR_API_KEY
      HOMEPAGE_VAR_READARR_API_KEY: $READARR_API_KEY
      HOMEPAGE_VAR_PORTAINER_API_KEY: $PORTAINER_API_KEY
    ports:
      - 80:3000
    volumes:
      - ~/server/homepage/config:/app/config
      - ~/server/homepage/images:/app/public/images
      - ~/server/homepage/icons:/app/public/icons
    restart: unless-stopped
    networks:
      - shared-network
      # - vpn-network

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      CONTAINERS: 1 # Allow access to viewing containers
      SERVICES: 1 # Allow access to viewing services (necessary when using Docker Swarm)
      TASKS: 1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      POST: 0 # Disallow any POST operations (effectively read-only)
    ports:
      - 2375:2375
      # - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
    networks:
      - shared-network
      - vpn-network



networks:
  vpn-network:
    name: vpn-network 
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
  shared-network:
    driver: bridge