services:

  hoarder:
    container_name: hoarder
    image: ghcr.io/hoarder-app/hoarder:release
    ports:
      - 3001:3000
    volumes:
      - /data/hoarder:/data
    environment:
      MEILI_ADDR: http://hoarder-meilisearch:7700
      BROWSER_WEB_URL: http://hoarder-chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
    restart: unless-stopped
    networks:
      - homelab

  hoarder-chrome:
    container_name: hoarder-chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    restart: unless-stopped
    networks:
      - homelab

  hoarder-meilisearch:
    container_name: hoarder-meilisearch
    image: getmeili/meilisearch:v1.11.1
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /data/hoarder-meilisearch:/meili_data
    restart: unless-stopped
    networks:
      - homelab
