services:
  transmission:
    image: linuxserver/transmission:4.1.0
    container_name: transmission
    devices:
      - /dev/net/tun
    volumes:
      - ${BASE_PATH}/config/transmission-home:/config
      - /data:/transcend # All the media containers use transcend internally because that's what i set originally. It's too much work to change it now.
    depends_on:
      - wireguard
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      PEERPORT: 54914
    healthcheck:
      test: ["CMD-SHELL", "transmission-remote localhost:9091 -n '${USER:-admin}:${PASS:-password}' -l || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    network_mode: "service:wireguard"

