services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      DOCKER_MODS: linuxserver/mods:universal-calibre # required for ebook conversion
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1 #optional
    volumes:
      - ~/server/config/calibre:/config
      - /data/media/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
    networks:
      - shared-network

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    # user: "1000:1000"
    # network_mode: "host"
    ports:
      - 8096:8096
    volumes:
      - ~/server/config/jellyfin/config:/config
      - ~/server/config/jellyfin/cache:/cache
      - type: bind
        source: /data/media
        target: /transcend/media # All the media containers use transcend internally because that's what i set originally. It's too much work to change it now.
    restart: "unless-stopped"
    # # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://192.168.0.32:8096
    # # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared-network

  jellystat-db:
    container_name: jellystat-db
    image: postgres:15.2
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
    - ~/server/config/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  jellystat:
    container_name: jellystat
    image: cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: $JWT_SECRET
    ports:
      - "3000:3000" #Server Port
    volumes:
      - ~/server/config/jellystat:/app/backend/backup-data
    depends_on:
      - jellystat-db
    restart: unless-stopped
