# services:

  # audiobookshelf:
  #   image: ghcr.io/advplyr/audiobookshelf:latest
  #   container_name: audiobookshelf
  #   ports:
  #     - 13378:80
  #   volumes:
  #     - /data/media/audiobooks:/audiobooks
  #     - ${BASE_PATH}/config/audiobookshelf/config/:/config
  #     - ${BASE_PATH}/config/audiobookshelf/metadata:/metadata
  #   environment:
  #     TZ: Etc/UTC
  #   restart: unless-stopped
  #   networks:
  #     - homelab

  # jellystat:
  #   container_name: jellystat
  #   image: cyfershepard/jellystat:latest
  #   environment:
  #     POSTGRES_USER: $POSTGRES_USER
  #     POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  #     POSTGRES_IP: jellystat-db
  #     POSTGRES_PORT: 5432
  #     JWT_SECRET: $JWT_SECRET
  #   ports:
  #     - 3000:3000 #Server Port
  #   volumes:
  #     - ${BASE_PATH}/config/jellystat:/app/backend/backup-data
  #   depends_on:
  #     - jellystat-db
  #   restart: unless-stopped
  #   networks:
  #     - homelab
  #
  # jellystat-db:
  #   container_name: jellystat-db
  #   image: postgres:15.2
  #   environment:
  #     POSTGRES_DB: $POSTGRES_DB
  #     POSTGRES_USER: $POSTGRES_USER
  #     POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  #   volumes:
  #   - ${BASE_PATH}/config/jellystat-postgres-data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - homelab
