services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ${BASE_PATH}/config/transmission/config:/config/transmission-home
      - ${BASE_PATH}/config/openvpn/config:/config/openvpn
      - /data:/transcend # All the media containers use transcend internally because that's what i set originally. It's too much work to change it now.
    environment:
      PUID: 1000
      PGID: 1000
      OPENVPN_CONFIG: se_all
      OPENVPN_PROVIDER: MULLVAD
      OPENVPN_USERNAME: $OPENVPN_USERNAME
      OPENVPN_PASSWORD: $OPENVPN_PASSWORD
      DISABLE_IPV6: true
      TRANSMISSION_WEB_UI_PORT: 9091
      LOCAL_NETWORK: 192.168.1.0/24
      TRANSMISSION_DOWNLOAD_DIR: /transcend/torrents # All the media containers use transcend internally because that's what i set originally. It's too much work to change it now.
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"  # This bypasses Docker weirdness with ipv6
    ports:  # map all svc you wanna route through VPN
      - 9091:9091 # Transmission Web UI
      # - 8191:8191 # Flaresolverr
      # - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      # - 6767:6767 # Bazarr
      - 5055:5055 # Jellyseerr
      # - 8787:8787 # Readarr Audiobooks
    restart: unless-stopped
    networks:
      - homelab
    labels:
      autoheal: true

