---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks
- Tailscale Bookmarks:
    - Actual Budget:
        - icon: actual-budget.png
          description: Finance Management
          href: https://actual-budget.{{HOMEPAGE_VAR_TAILNET}}
    - Dockhand:
        - icon: dockhand.png
          description: Container Management
          href: https://dockhand.{{HOMEPAGE_VAR_TAILNET}}
    - Jellyseerr:
        - icon: jellyseerr.png
          description: Media search
          href: https://jellyseerr.{{HOMEPAGE_VAR_TAILNET}}
    - Jellyfin:
        - icon: jellyfin.png
          description: Media server
          href: https://jellyfin.{{HOMEPAGE_VAR_TAILNET}}
    - Audiobookshelf:
        - icon: audiobookshelf.png
          description: Audiobooks library
          href: https://audiobookshelf.{{HOMEPAGE_VAR_TAILNET}}
    - Calibre-Web:
        - icon: calibre.png
          description: ebooks library
          href: https://calibre-web.{{HOMEPAGE_VAR_TAILNET}}
    - Sonarr:
        - icon: sonarr.png
          description: TV Shows Management
          href: https://sonarr.{{HOMEPAGE_VAR_TAILNET}}
    - Radarr:
        - icon: radarr.png
          description: Movies Management
          href: https://radarr.{{HOMEPAGE_VAR_TAILNET}}
    # - Lazylibrarian:
    #     - icon: lazylibrarian.png
    #       description: Audiobook Management
    #       href: https://lazylibrarian.{{HOMEPAGE_VAR_TAILNET}}
    - FossFLOW:
        - icon: flowise.png
          description: System Diagrams
          href: https://fossflow.{{HOMEPAGE_VAR_TAILNET}}
    # - Bazarr:
    #     - icon: bazarr.png
    #       description: Subtitles Management
    #       href: https://bazarr.{{HOMEPAGE_VAR_URL}}
    # - Prowlarr:
    #     - icon: prowlarr.png
    #       description: Torrent Indexer Service
    #       href: https://prowlarr.{{HOMEPAGE_VAR_URL}}
    # - Stirling PDF:
    #     - icon: stirling-pdf.png
    #       description: PDF Tools
    #       href: https://stirling-pdf.{{HOMEPAGE_VAR_URL}}
    # - Jellystat:
    #     - icon: jellystat.png
    #       description: Jellyfin Statistics
    #       href: https://jellystat.{{HOMEPAGE_VAR_URL}}
    # - Transmission:
    #     - icon: transmission.png
    #       description: Torrent Download Client
    #       href: https://transmission.{{HOMEPAGE_VAR_URL}}
