---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

dockerproxy:
  host: dockerproxy
  port: 2375
# dockerproxy:
#   socket: /var/run/docker.sock
