---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media Server:
    - Jellyseerr:
        icon: jellyseerr.png
        description: "Media search"
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:5055
        server: dockerproxy
        container: app-jellyseerr
        widget:
          type: jellyseerr
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:5055
          key: {{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}
    - Jellyfin:
        icon: jellyfin.png
        description: "Media server"
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8096/
        server: dockerproxy
        container: app-jellyfin
        widget:
          type: jellyfin
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          # enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    # - Audiobookshelf:
    #     icon: audiobookshelf.png
    #     description: "Audiobooks library"
    #     href: http://{{HOMEPAGE_VAR_HOST_IP}}:13378
    #     server: dockerproxy
    #     container: audiobookshelf
    #     widget:
    #       type: audiobookshelf
    #       url: http://audiobookshelf
    #       key: {{HOMEPAGE_VAR_AUDIOBOOKSHELF_API_KEY}}
    - Calibre:
        icon: calibre.png
        description: "ebooks library"
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8083
        server: dockerproxy
        container: app-calibre-web
        widget:
          type: calibreweb
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:8083
          username: {{HOMEPAGE_VAR_CALIBRE_USERNAME}}
          password: {{HOMEPAGE_VAR_CALIBRE_PASSWORD}}

- Servarr:
    - Transmission:
        icon: transmission.png
        description: "Torrent Download Client"
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:9091
        server: dockerproxy
        container: transmission
        widget:
          type: transmission
          url: http://wireguard:9091
          username: ""
          password: ""
          rpcUrl: "/transmission/"
    - Sonarr:
        icon: sonarr.png
        description: "TV Shows Management"
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8989
        server: dockerproxy
        container: app-sonarr
        widget:
          type: sonarr
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:8989
          key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
    - Radarr:
        icon: radarr.png
        description: "Movies Management"
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:7878
        server: dockerproxy
        container: app-radarr
        widget:
          type: radarr
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:7878
          key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
    # - Readarr Audiobooks:
    #     icon: readarr.png
    #     description: "Audiobook Management"
    #     href: http://{{HOMEPAGE_VAR_HOST_IP}}:8787
    #     server: dockerproxy
    #     container: readarr-audiobooks
    #     widget:
    #       type: readarr
    #       url: http://wireguard:8787
    #       key: {{HOMEPAGE_VAR_READARR_API_KEY}}
    # - Readarr ebooks:
    #     icon: readarr.png
    #     description: "ebook Management"
    #     href: http://{{HOMEPAGE_VAR_HOST_IP}}:8788
    #     server: dockerproxy
    #     container: readarr-ebooks
    #     widget:
    #       type: readarr
    #       url: http://readarr-ebooks:8787
    #       key: {{HOMEPAGE_VAR_READARR_API_KEY}}
    # - Bazarr:
    #     icon: bazarr.png
    #     description: "Subtitles Management"
    #     href: http://{{HOMEPAGE_VAR_HOST_IP}}:6767
    #     server: dockerproxy
    #     container: bazarr
    #     widget:
    #       type: bazarr
    #       url: http://wireguard:6767
    #       key: {{HOMEPAGE_VAR_BAZARR_API_KEY}}
    - Prowlarr:
        icon: prowlarr.png
        description: "Torrent Indexer Service"
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:9696
        server: dockerproxy
        container: prowlarr
        widget:
          type: prowlarr
          url: http://wireguard:9696
          key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}

- Tools:
    - Pihole:
        icon: pi-hole.png
        description: "Network-wide Ad Blocking"
        href: http://192.168.0.150:80/admin
        widget:
          type: pihole
          url: http://192.168.0.150:80
          version: 6
          key: {{HOMEPAGE_VAR_PIHOLE_PASSWORD}}
    - Home Assistant:
        icon: home-assistant.png
        description: Home Assistant
        href: http://192.168.0.92:8123
        widget:
          type: homeassistant
          url: http://192.168.0.92:8123
          key: {{HOMEPAGE_VAR_HOME_ASSISTANT_TOKEN}}
          custom:
            - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }}"
              label: switches on
            - state: weather.forecast_home
              label: wind speed
              value: "{attributes.wind_speed} {attributes.wind_speed_unit}"
    # - Stirling PDF:
    #     icon: stirling-pdf.png
    #     description: "PDF Tools"
    #     href: http://{{HOMEPAGE_VAR_HOST_IP}}:8080
    #     server: dockerproxy
    #     container: stirling-pdf
    # - Jellystat:
    #     icon: jellystat.png
    #     description: "Jellyfin Statistics"
    #     href: http://{{HOMEPAGE_VAR_HOST_IP}}:3000
    #     server: dockerproxy
    #     container: jellystat
    - Actual-Budget:
        icon: actual-budget.png
        description: "Personal Finance Manager"
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:5006
        server: dockerproxy
        container: app-actual-budget
    - Dockhand:
        icon: dockhand.png
        description: "Docker Management UI"
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8002
        server: dockerproxy
        container: app-dockhand
        widget:
          type: dockhand
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:8002
          username: root
          password: R^yNiVNBKhtdR3&Aeye2
